matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSIONS="3.0 3.0.1 3.0.2 3.1 3.1.1 4.0-DEVELOPMENT-SNAPSHOT-2017-06-23-a"
        - SWIFTENV_ROOT="$HOME/.swiftenv"
        - PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Unreachable"
install: ./ci/install.sh
script: ./ci/travis.sh
